backend:
  name: git-gateway

media_folder: site/static/img # Folder where user uploaded files should go
public_folder: img

collections: # A list of collections the CMS should be able to edit
  - name: pages
    label: Pages
    files:
      - file: site/content/_index.md
        label: Dialogen konfiguration
        name: home
        fields:
          - {label: Huvudrubrik, name: title, widget: string}
          - {label: Beskrivning av hemsidan, name: description, widget: string}
          - {label: Bakgrundsbild, name: image, widget: image}
          - {label: Kontakt, name: contact, widget: object, fields: [
              {label: Namn, name: name},
              {label: Adress, name: address},
              {label: Telefon nr., name: phone},
              {label: E-post, name: email},
            ]}
          - {label: Företagsinfo, name: info, widget: object, fields: [
              {label: Bild, name: image, widget: image},
              {label: Text, name: text, widget: text}
            ]}
          - {label: Om Företaget, name: blurbs, widget: list, fields: [
              {label: Bild, name: image, widget: image},
              {label: Text, name: text, widget: text}
            ]}
          - {label: Länkar, name: sections, widget: list, fields: [
              {label: Bild, name: image, widget: image},
              {label: Rubrik, name: title, widget: string},
              {label: Text, name: text, widget: text},
              {label: Länktext, name: linkText, widget: string, required: false},
              {label: länk, name: link, widget: string, required: false}
            ]}
          - {label: Social Media, name: socialmedia, widget: object, fields: [
              {label: Facebook länk, name: facebook, widget: string, required: false},
              {label: Instagram länk, name: instagram, widget: string, required: false}
            ]}
